#
# Docker compose for development environment
#

services:
  database:
    image: library/postgres:16.1
    ports:
      - "5432:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql

  http-router:
    build:
      context: ./http-router
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"